# Generated by Django 5.0.2 on 2024-05-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_order_user_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
