# Generated by Django 5.1.1 on 2024-09-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0015_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
