# Generated by Django 5.1.1 on 2024-09-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0016_remove_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
