# Generated by Django 5.0.3 on 2024-09-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0018_order_razorpay_amount_order_razorpay_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
